In [23]:
import numpy as np


def WhiteWash(matrix):
    #Create new matrix, as to not change the old one
    newMatrix = np.zeros((matrix.shape[0],3))
    
    #Checking for matrices of the wrong dimensions
    if (matrix.shape[1] != 3):
        print("Invalid Matrix")
        return matrix
    
    #Checking for matrices w/ invalid indices
    for x in range(matrix.shape[0]):
        for y in range(matrix.shape[1]):
            if (0 > matrix[x][y] > 1):
                print("Invalid Matrix")
                return matrix 
            
    #Fills array w/ Whitewashed values        
    for x in range(matrix.shape[0]):
        for y in range(matrix.shape[1]):
            newMatrix[x][y] = (matrix[x][y] + 1)/2
    
    return newMatrix
    
matrix = np.random.rand(10,3)
print(matrix)
print(WhiteWash(matrix))




[[ 0.84422619  0.16839427  0.20341666]
 [ 0.44872615  0.16103716  0.70405567]
 [ 0.71176258  0.16598972  0.22085038]
 [ 0.54980581  0.68202747  0.74988185]
 [ 0.1598318   0.68792788  0.69842765]
 [ 0.03601097  0.16831658  0.05953151]
 [ 0.12408201  0.59382736  0.33974833]
 [ 0.80680822  0.56938115  0.74345796]
 [ 0.12508795  0.92691252  0.72780823]
 [ 0.67937138  0.19197737  0.05383206]]
[[ 0.92211309  0.58419713  0.60170833]
 [ 0.72436307  0.58051858  0.85202784]
 [ 0.85588129  0.58299486  0.61042519]
 [ 0.77490291  0.84101374  0.87494092]
 [ 0.5799159   0.84396394  0.84921382]
 [ 0.51800548  0.58415829  0.52976575]
 [ 0.562041    0.79691368  0.66987416]
 [ 0.90340411  0.78469057  0.87172898]
 [ 0.56254397  0.96345626  0.86390412]
 [ 0.83968569  0.59598868  0.52691603]]
